#!/bin/sh
# An alarm based on The Kit
#
#  Copyright (C) 2021 Zhang Maiyun <me@myzhangll.xyz>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

DELAY1=0.3
DELAY2=1
TTY=/dev/ttyACM0

SAY()
{
    espeak -zp30 -g2 "$@" > /dev/null
}

blink()
{
    echo light_on > "$TTY"
    head -n1 "$TTY" > /dev/null
    sleep "$DELAY1"
    echo light_off > "$TTY"
    head -n1 "$TTY" > /dev/null
}

for _ in $(seq 5)
do
    blink
    sleep "$DELAY2"
done

temperature="$( (head -n1 "$TTY" & sleep 0.1; echo get_info > "$TTY") | jq .tempC)"

SAY "get up immediately!"
SAY "the temperature now is $temperature degrees Celsius."

if [ "$(echo "$temperature < 25.0" | bc)" -eq 1 ]
then
    SAY "dress warm!"
elif [ "$(echo "$temperature < 32.0" | bc)" -eq 1 ]
then
    SAY "nice weather!"
else
    SAY "stay hydrated!"
fi
